### PR TITLE
Revamp presentation of EmuDesk dialogs

### PR DESCRIPTION
**Pull request by chrilith**
Hi everyone,

I spent some days trying to improve readability and presentation of most if not all the dialogs of EmuDesk in all languages.
Main work was to add some missing spaces that squashed dialogs in low resolution, but more work has been done on ADINSDSK, ADINSWIN and for the most revamped ADDESKCF.

In the meantime, I also tried to fix some translation errors, too long strings, and missing spaces mainly in menu entries and all changed dialogs have been tested with all languages too.

Hopefully you'll like them and eventually merge everything :)

Thank you for reading and for the great work done on this project.
Happy holydays!

### CODE REVIEW

**Comment by czietz** [comment]
Thank you. I appreciate the commit and the huge effort that must have gotten into it. I will review it to see if I spot any problems.

May I ask, though: You changed translations for several languages. How confident would you rate these changes? Should I have them double-checked by our translators, which are usually native speakers of the respective language?

FYI: I also posted about your PR on our mailing list: https://sourceforge.net/p/emutos/mailman/emutos-devel/. Feel free to join any discussion there, too.

**Comment by chrilith** [comment]
Hi czietz,

Indeed, I haven't talk about those changes specifically, sorry.

I saw that sometimes a same string was used for different items in a same dialog, I then considered this a mistake and tried to find a proper translation. For this, I searched in the current translation file for a corresponding expression, if not found, I checked Google translate and then search Google to check if the candidate translation was usable in this context. When a string was too long, I did the same, but is that case there is generally a corresponding entry in the translation file.

But of course, I cannot guarantee a correct translation and this must be validated by native speakers indeed.
Changed files are CS, FR, HU, GR, PL, RU, TR, others are mainly related to added spaces for alignment.

Hopefully I haven't break anything in the meaning of these expressions. I know how time consuming it is to translate everything.

Thanks.

**Comment by czietz** [comment]
Merged with commit dacb593c946b7a6055d49b40fa95da6713dc0611. Thank you for your great work!

**Comment by chrilith** [comment]
Hi czietz,

Thank you for the merge!

Regards,

**Pull request closed without merging**
