### PR TITLE
Romanian translation

### PR DESCRIPTION
**Pull request by Dragan232**
Greetings, this edit adds Romanian (code 24) with keyboard.

### CODE REVIEW

**Comment by czietz** [comment]
Thank you very much for your contribution! I'll come back with a review (if necessary); but it might take me a few days to do so.

If I may ask: Would you be willing to support the Romanian translation in the long term? Typically, before a release (which happens roughly once a year), we ask all translators to provide updated translations.

**Comment by Dragan232** [comment]
As long as nothing prevents me, yes.

**Comment by th-otto** [comment]
There are a few problems with your ro.po file. First of, it has CR/LF endings. Then, there are syntax errors in it. Dunno whether they are caused by "bug" (the emutos tool that extract the strings), or by your editing:

```
 "Unitatea %c: nu r�spunde.|"
 "Verifica�i unitatea de discuri|"
 "sau introduce�i un disc.]"
-"[Anula�i|Re�ncerca�i]
+"[Anula�i|Re�ncerca�i]"
 
 #: aes/gem_rsc.c
 msgid "[1]["
@@ -143,7 +143,7 @@
 "[Cancel|Retry]"
 msgstr "[1]["
 "Este posibil ca datele de pe|"
-"discul din unitatea %c: s�|
+"discul din unitatea %c: s�|"
 "fie deteriorate.]"
 "[Anula�i|Re�ncerca�i]"
 
@@ -1188,7 +1188,7 @@
 "No drive identifier.]"
 "[ Retry ]"
 msgstr "[1]["
-"Nu exist� un identificator|
+"Nu exist� un identificator|"
 "de unitate.]"
 "[Re�ncerca�i]"
```

And in case you did not know, on http://tho-otto.de/rscview/emutos.php you can upload your po file (by selecting it at the bottom, then using the "Test translation" button). I've just updated the tool to use the correct character set for "ro". That tool spits out some warnings:

```
desktop.rsc: untranslated: '  Eject floppy'
tree ADDINFO, object DELABEL: overlaps with object DEVERSN in translation of 'Version' to 'Versiunea'
tree ADINSAPP, object #6: overlaps with object APAUTO in translation of 'Boot status:' to 'Starea de pornire:'
desktop.rsc: translated 265, untranslated 1
Warning: alert button #0 in translation of STPRTERR exceeds TOS standard length 10
Warning: alert button #1 in translation of STFOFAIL exceeds TOS standard length 10
Warning: alert button #0 in translation of STFMTERR exceeds TOS standard length 10
Warning: alert button #0 in translation of STDRIVID exceeds TOS standard length 10
Warning: alert button #1 in translation of STDELFIL exceeds TOS standard length 10
Warning: alert button #1 in translation of STDELDIR exceeds TOS standard length 10
Warning: alert button #1 in translation of STOPFAIL exceeds TOS standard length 10
Warning: alert button #1 in translation of STCRTFIL exceeds TOS standard length 10
Warning: alert button #0 in translation of STRENAME exceeds TOS standard length 10
Warning: alert line #0 in translation of STDUPCUT exceeds TOS standard lengt

gem.rsc: translated 20, untranslated 0
Warning: alert button #1 in translation of AL00CRT exceeds TOS standard length 10
Warning: alert button #1 in translation of AL01CRT exceeds TOS standard length 10
Warning: alert button #1 in translation of AL02CRT exceeds TOS standard length 10
Warning: alert button #1 in translation of AL03CRT exceeds TOS standard length 10
Warning: alert button #1 in translation of AL04CRT exceeds TOS standard length 10
Warning: alert line #1 in translation of AL18ERR exceeds TOS standard length 32
Warning: alert button #1 in translation of AL00CRT exceeds TOS standard length 10
Warning: alert button #1 in translation of AL01CRT exceeds TOS standard length 10
Warning: alert button #1 in translation of AL02CRT exceeds TOS standard length 10
Warning: alert button #1 in translation of AL03CRT exceeds TOS standard length 10
Warning: alert button #1 in translation of AL04CRT exceeds TOS standard length 10
Warning: alert line #1 in translation of AL18ERR exceeds TOS standard length 32
```

Maybe you want to have a look at them. The "  Eject Floppy" string is only used for the lisa target IIRC.

BTW, should we add your keyboard table also to FreeMiNT?

**Comment by th-otto** [comment]
Looks like there are a lot of deadkeys. Both EmuTOS & Mint can support them.

**Comment by Dragan232** [comment]
> Looks like there are a lot of deadkeys. Both EmuTOS & Mint can support them.

The dead keys can be ignored, as they're not used for typing Romanian, usually for foreign languages like ˇ + s = š.

**Comment by Dragan232** [comment]
Notice: Conversation abruptly stopped, no action was taken, 3 days passed.

**Comment by czietz** [comment]
Sorry, but - as noted above - I need time to review your changes. Rest assured that you are not forgotten.

**Comment by Dragan232** [comment]
Thanks for confirming that you are checking.

**Comment by czietz** [comment]
Again, I would like to thank you for the big effort you put into the Romanian translation. We also like when EmuTOS gets even more multi-lingual.

However, there are a few points that need to be rectified before I could merge your PR.

1. I suppose you built a Romanian version of EmuTOS yourself, e.g., by running `make 256 UNIQUE=ro`? How did you do that? The code from this PR unfortunately fails to build:
```
./localise -uro  localise.ctl bios/ctables.h localise1.tmp
invalid character set ro specified for country ro in control file
m68k-atari-mint-gcc -m68000 -mshort -Os -fomit-frame-pointer -fno-common -Wall -Werror=undef -Werror=missing-prototypes -Werror=strict-prototypes -Werror=implicit-function-declaration -Werror=format -Werror=redundant-decls -Werror=format-extra-args -Werror=old-style-definition -Werror=type-limits -Iinclude -DWITH_AES=1 -DWITH_CLI=1 -DTARGET_256 -c bios/startup.S -o obj/startup.o
bios/startup.S:11:27: fatal error: ../obj/header.h: No such file or directory
compilation terminated.
```
This is due to the character set / font "ro" that you specified in localise.ctl. I assume the correct setting for the charset might be "l2" (i.e., "latin2"), like for Czech, Polish and Hungarian.

2. In the version of "keyb_ro.h" in this PR, you accidentally defined `keytbl_pl_caps` instead of `keytbl_ro_caps`.

**Comment by Dragan232** [comment]
1. No, I haven't "built" a version using a compiling tool. Will try your advice to fix it.
2. My mistake, will be fix in the commit below.

**Comment by Dragan232** [comment]
1. No, I haven't "built" a version using a compiling tool. Will try your advice to fix it.
2. My mistake, will be fix in the commit below.

**Comment by czietz** [comment]
Now it builds. 

Could you please double-check the translation of the buttons for "Default" in this dialog:
grab0001

Is is supposed to read "Dďż˝faut"?

**Comment by czietz** [comment]
Furthermore, unfortunately one text is slightly to long in this dialog:
grab0002

**Comment by czietz** [comment]
Another string is slightly too long and needs to be shortened (found by @th-otto's website that he recommended you):
grab0003

(This only becomes visible for releases, so it's a bit tricky to spot.)

**Comment by Dragan232** [comment]
1. No, this was just me using French (with broken encoding due to GitHub) as a base, it is meant to be Implicit.
2. This can will be changed to Starea de boot.
3. This one is more tricky, Ediție (Edition) will have to suffice.

**Comment by czietz** [comment]
Could you please make a commit with the required changes and add it to this PR?

Also, when you're editing ro.po anyway, please add two empty lines at the end, as this is required by the tools that read the file. (You can check the other .po files if it's unclear what I meant.)

**Comment by Dragan232** [comment]
Done. There are two 0A bytes at the end (new lines), but GitHub doesn't show them well for some reason.

**Comment by czietz** [comment]
Looking good now. Thank you for your work and your prompt replies to my review comments! I intend to merge your PR during the next days.

Only two formalities left: How do you want to be mentioned in doc/authors.txt? Do you mind sharing your email address with me so that I can contact you before a release, if any translations need updating? If you don't want to post your email address publicly, feel free to send me a mail instead: czietz _at_ gmx.net

**Comment by Dragan232** [comment]
They are in provided in the ro.po file.

**Comment by czietz** [comment]
Merged with commit 4999576.

**Pull request closed without merging**
