### PR TITLE
Optimized version of the add_partition() function:

### PR DESCRIPTION
**Pull request by Schwarzemann**
I moved the declaration of logical and b to the same line, since they are only used together. I replaced the strcmp() calls with direct comparisons of the characters in the id string, which should be faster since we know the length is always 3. I used memcpy() instead of assigning each character individually to b->id, which should be faster for larger strings. I removed the unnecessary check for the null terminator in id, since we know it always has length 3. I added braces around the if block for setting the GETBPB_ALLOWED flag, for consistency and readability. I removed the commented-out code for making only GEM/BGM partitions visible to applications, since it was not actually being used.

### CODE REVIEW

**Comment by czietz** [comment]
Welcome and thank you for your contribution.

However, I’m afraid I have a few questions and objections that need to be discussed. The line numbers refer to your version (green line numbers) of the file in https://github.com/emutos/emutos/pull/37/commits/d8ba2ae936c51643fc512a971681fe642fbb7bae.

**General question**: Why did you chose this function for optimization in the first place? Imho, it’s not time critical.

**l. 354, l. 360**: In the EmuTOS code base, we prefer to declare variables (in this case: `logical` and `b`) at the beginning of a block, not somewhere within the code. Hence, such constructs as you use should be avoided.

**l. 361, l. 376**: While I agree that using curly braces even for one-line if statements is good coding practice, we try to at least keep the coding style uniform within a file. So just changing it in one function – whereas the rest of blkdev.c is unchanged – should be avoided.

**l. 368, l. 380**: One the one hand, you changed a manual assignment to a `memcpy`, which maybe makes the intent clearer. But on the other hand, you changed a `strcmp` to a very verbose manual comparison. I think the latter should be avoided. (And see below for another comment w.r.t. this line.)

**l. 384**: Why did you remove the comment?

**l. 380**: The most critical point: **Here you changed the functionality to only allow GEM/BGM partitions**, which obviously breaks a lot of functionality in EmuTOS, such as DOS partition support. This is clearly flawed and needs to be reverted.

**Comment by Schwarzemann** [comment]
I was just looking through the source code and saw this function and wanted to optimize it. I know it's not critical but still I just wanted to work on it. About your other concerns, I will just rewrite it and submit it later.

**Comment by vinriviere** [comment]
Hi @Schwarzemann ,

Generally speaking, we don't change the code if that doesn't bring some real-world benefit.
- You moved variables declarations near their first usage. This is usually a good thing, unfortunately this is a C99 feature, while EmuTOS sources currently target C89. So that's unsuitable.
- You added braces around single-instruction blocks. This is a matter of style. In current EmuTOS sources, we don't do that systematically.
- You removed some spaces in variable assignment. Sometimes a few spaces are willingly added for alignment. Again, that's a matter of style.
- You removed a comment at the end "/* mark device as used */", I don't see any benefit for that.
- Replacing partition type assignment from testing 3 bytes to using memcpy() is semantically better. But I'm pretty sure it is slower. And I'm not sure if this actually generates smaller code (to be tested). It is important to keep the generated code as small as possible, specially for the 192k ROMs.

So if you provide patches with only some cleanups (from your point of view), they are unlikely to be accepted.
On the other hand, compact patches to fix actual bugs are highly appreciated.

**Comment by czietz** [comment]
I'm closing this due to inactivity. You can always open a new PR when your patch follows the guidelines explained above.

**Pull request closed without merging**
