### PR TITLE
Expected Polish translation

### PR DESCRIPTION
**Pull request by Avstraliya**

### CODE REVIEW

**Comment by anodynesoftware** [comment]
Thank you for offering to make a Polish translation of EmuTOS :-)  If you haven't yet joined the mailing list, we strongly encourage you to do so. Some other things to bear in mind:
1. We are always changing or adding text in EmuTOS. So we need translators to be willing to continue to maintain the translations over time. We do not update the translations until "just before" a new release, so at that time, we'll request translations of the changed text from all the official translators. Of course, you are never obliged to do that, but if the translation is not maintained, we will normally drop that language in the next release.
2. Any commit must compile clean & be tested, so no partial commits please. I would expect just one commit for the complete translation.
3. When translating things like alerts, there are special formatting rules that you need to bear in mind.  Unless you're already an Atari programmer, they will not be obvious. If you join the mailing list and say hello to everyone, I can email you with a list of things to know.

Roger Burrows

**Comment by Avstraliya** [comment]
Good! I understand that Atari ST EmuTOS might use some text doohickery. I used the same codepage as the Czech translation (ISO Latin-2)

**Comment by Avstraliya** [comment]
Also, I think it auto-added me, since I received the notific. about this thru Gmail.

**Comment by anodynesoftware** [comment]
Ah, we're not as sophisticated as that. You must have got the response from GitHub. Here's the URL where you can join the EmuTOS list:
https://sourceforge.net/projects/emutos/lists/emutos-devel
See you on the list!

**Comment by Avstraliya** [comment]
I am now on the list

W dniu piątek, 3 kwietnia 2020 Roger Burrows <notifications@github.com>
napisał(a):

**Comment by Avstraliya** [comment]
Well, the files have been made.

**Pull request closed without merging**
